### ISSUE TITLE
Добавить текстовое поле для описания в меню

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#12]
Необходимо добавить на страницы редактирования элементов раздела "Меню" поле "Описание" с текстовым редактором, аналогичное тому, что добавлено в "Категории" 
![image](https://user-images.githubusercontent.com/8628465/41662452-e0e6fda0-74a9-11e8-8e8c-6539fc06b9af.png)

Сделать вывод контента этого поля на страницу меню на сайте, аналогично как реализовано для категорий. 
![image](https://user-images.githubusercontent.com/8628465/41662470-e9bb3810-74a9-11e8-986a-4d2af08ed850.png)

**Comment by Sadykov70** [comment]
Обнаружил баг: в категории нельзя прикрепить картинку в поле описания
![image](https://user-images.githubusercontent.com/38241587/41722346-ef0d2d9c-7570-11e8-9e55-31e52545ac58.png)
