### ISSUE TITLE
Семантическая разметка товаров и изменение вывода изображений

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#15]
Описание задачи:
https://docs.google.com/document/d/1MuOeVPr1BsTGn5ZXR7j9j0Aa63ZnTGk3OISlZvTG3Dg/edit

Необходимо заменить вывод изображений в товарах: выводить не в значениях свойства CSS “background-image”, а напрямую в теге IMG с указанием атрибутов alt и title, соответствующих H1 товара.

**Микроразметка Schema.org**

https://yandex.ru/support/webmaster/schema-org/what-is-schema-org.html

Карточку товара необходимо разметить по стандарту Shcema.org с использованием типа Product https://schema.org/Product и свойствами:

- name (в теге H1)
- description (только если у товара есть описание, в теге product__description)
- lowPrice (цена от. Значение поместить в тэг LINK и убрать форматирование отображения, чтобы в значении отсутствовали пробелы. Разделитель дробной части - точка.)
- image (в теге IMG)
- priceCurrency (также поместить в тег LINK)
- availability (статус наличия, также в тег LINK)

**Разметка Open Graph**

https://yandex.ru/support/webmaster/open-graph/intro-open-graph.html

- og:title
- og:image
- og:url
- og:type
- website
- og:locale (в зависимости от домена выставлять свой языковой код)
- og:site_name
- Furniprice

**Comment by devawpshko** [comment]
Дополнил файл примерами разметки: для schema.org указал тэги с классами, куда вставляются свойства.

**Comment by devawpshko** [comment]
Нужно внести исправления в микроразметку Schema товаров, в частности:
1) убрать `itemprop="offerCount"` из тэга `<strong class="highlight _purple">`
2) перенести из блока `<head>` тэги
```
<link itemprop="lowPrice" content="32105.61">
<link itemprop="priceCurrency" content="RUB">
<link itemprop="availability" href="http://schema.org/InStock">
```
внутрь блока
`<div class="product__price" itemprop="offers" itemscope="" itemtype="http://schema.org/AggregateOffer">`

**Comment by Sadykov70** [comment]
надо сделать после задачки https://github.com/otrada-a/furniprice/pull/2200

**Comment by devawpshko** [comment]
REMINDER: пересмотреть после выкладки новой карточки
