### ISSUE TITLE
Скрытие разделов меню, не содержащих товаров

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#16]
В разделах рубрикатора представлены категории, не содержащие товаров. Такие страницы могут негативно влиять на ранжирование. Не относится к тэговым страницам - только для разделов меню.

Что нужно сделать, если в разделе меню нет привязанных (отобранных товаров):
* Скрыть ссылку на раздел меню в рубрикаторе и родительской странице;
* Не выводить страницу в карте сайта sitemap.xml
* Добавить на страницу между тегов `<head></head>` meta-тег `<meta name="robots" content="noindex,nofollow">`

Если родительский раздел содержит дочерние разделы, в которых нет привязанных товаров (пустые), то скрываются и дочерние разделы, и родительский.

**Comment by Sadykov70** [comment]
нужно добавить мета теги на пустые страницы
