### ISSUE TITLE
Настроить код ответа 404 для несуществующих страниц

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#17]
При обращении к несуществующим страницам, например https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/osveshchenie-dlia-gostinoi/gagagagnaugau/  выполняется 302 редирект на главную страницу. Для несуществующих адресов (некорректных) должен отдаваться 404 ответ с показом страницы-заглушки и информацией, что адрес введен неверно или страница не существует.
Пример - https://nn.vseinstrumenti.ru/uborka/moyuschie_chistyaschie_sredstva/sfagaga/

**Comment by grachevko** [comment]
У нас под разные языки сделаны разные меню. 
В данный момент этих меню всего 2, одна для русского языка и одна по умолчанию для всех остальных языков.

Таким образом, если перейти в любой раздел меню на английском языке и переключится на русский, то в русском языке такой ссылки не существует. 
Руководство поставило задачу, что если при смене языка не находиться меню то кидать на главную.

**Comment by Sadykov70** [comment]
Duplicate of https://github.com/otrada-a/seo/issues/17
