### ISSUE TITLE
Значение Title, Description, H1 по умолчанию

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#2]
Если в категории не заполнены поля блока SEO: Заголовок (H1), Заголовок страницы (Page title), Описание (Page description), то необходимо использовать значения по умолчанию:
Для H1 - поле "Название"
Для Title - шаблон "%Название% - цены, отзывы, доставка по России."
Для Description - шаблон "Посмотреть %название% в каталоге Furniprice: огромный выбор, доступные цены, удобная доставка по России в короткие сроки."
где %название% - значение поля "Название"

Если в родительской рубрике заданы шаблоны для вложенных рубрик "Шаблон формирования Page title" или "Шаблон формирования meta description", то они должны иметь приоритет над общим шаблоном по умолчанию.

Приоритеты полей (по убыванию важности):
1. Поле заполнено персонально для категории
2. Заполнены поля шаблонов в родительской категории
3. Используется поле по умолчанию

Значения полей по умолчанию (H1, Title, Description) должны быть редактируемыми в админке. Нужно добавить соответствующий пункт в разделы админки. 
Должна быть возможность использовать шорткоды, которые должны были быть сделаны для использования в полях "Шаблон формирования Page title" или "Шаблон формирования meta description". Прошу также добавить подсказки для этих полей с указанием, как записывать шорткоды в поля.

**Comment by grachevko** [comment]
Шорткоды для шаблонов товаров:
```
{{ name }}
{{ price }}
{{ parent_name }}
{{ product_prefix }}
```
