### ISSUE TITLE
Недоступны файлы sitemap

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#22]
При обращении к файлам sitemap отдается 404 ошибка, пример:
https://www.furniprice.ru/sitemap.xml
https://www.furniprice.ru/sitemap.default.xml
https://www.furniprice.ru/sitemap.articles.xml
и все остальные. Нужно восстановить их доступность.

**Comment by grachevko** [comment]
Была утечка памяти при генерации файлов. Исправлено.

**Comment by grachevko** [comment]
Все ссылки доступны. Если с сайтмапом что-то ещё, создавайте отдельную задачу с описанием.
