### ISSUE TITLE
Проставить мета-теги в меню региональных поддоменов

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#26]
Для всех региональных поддоменов необходимо установить значения полей блока "Шаблоны для Seo" в меню для разделов 1го уровня:

- Мебель для дома (item_id = 1, id = 1)
- Мебель для Улицы (item_id = 663, id = 2)
- Освещение (item_id = 3, id = 676)
- Аксессуары и Декор (item_id = 4, id = 680)

Поле "Заголовок страницы (Title)"
`{{ product_prefix }} {{ name }}: купить в {{ location_where }} по цене {{ price }}`

Поле "Описание (Meta description)"
`{{ name }} - {{ product_prefix }} стоимостью от {{ price }}. Заказать в интернет-магазине Furniprice с доставкой в {{ location_to }} в короткие сроки.`

**Comment by Sadykov70** [comment]
@devawpshko это все реализуется через админку -> SEO Регионы

**Comment by devawpshko** [comment]
@Sadykov70 да, но там 1000+ регионов, по 4 корневых раздела - это 4000+ страниц нужно отредактировать

**Comment by grachevko** [comment]
@Sadykov70 напиши sql запрос, я его выполню на базе

**Comment by devawpshko** [comment]
В БД эти данные хранятся в 1 таблице? В каком виде?
ID / ID_региона / ID_меню / ID_поля / value ?

**Comment by devawpshko** [comment]
@Sadykov70 В БД эти данные хранятся в 1 таблице? В каком виде?
ID / ID_региона / ID_меню / ID_поля / value ?

**Comment by Sadykov70** [comment]
@devawpshko да, в одной таблице, а к чему вопрос?)

**Comment by Sadykov70** [comment]
```
CREATE PROCEDURE loopLocations()
BEGIN
  DECLARE loc_done INT DEFAULT 0;
  DECLARE loc_id INT;
  DECLARE loc_cur CURSOR FOR SELECT id FROM seo_location sl where domain = 'furniprice.ru';
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET loc_done = 1;

  OPEN loc_cur;

  location_loop: LOOP
    FETCH loc_cur INTO loc_id;

    IF loc_done = 1 THEN
      LEAVE location_loop;
    END IF;

    CALL loopMenuItems(loc_id);

  END LOOP location_loop;

  CLOSE loc_cur;
END;

CREATE PROCEDURE loopMenuItems(IN loc_id INT)
  BEGIN
    DECLARE itm_done INT DEFAULT 0;
    DECLARE itm_id INT;
    DECLARE itm_cur CURSOR FOR SELECT id FROM catalog_menu_item cmi where parent_id is null and activated = 1 and menu_id = 1;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET itm_done = 1;

    OPEN itm_cur;

    menu_item_loop: LOOP
      FETCH itm_cur INTO itm_id;

      IF itm_done = 1 THEN
        LEAVE menu_item_loop;
      END IF;

      INSERT INTO seo_location_menu_item (menu_item_id, location_id, seo_templates_title, seo_templates_description)
      VALUES (itm_id, loc_id, '{{ product_prefix }} {{ name }}: купить в {{ location_where }} по цене {{ price }}', '{{ name }} - {{ product_prefix }} стоимостью от {{ price }}. Заказать в интернет-магазине Furniprice с доставкой в {{ location_to }} в короткие сроки.');

    END LOOP menu_item_loop;

    CLOSE itm_cur;
  END;

CALL loopLocations();

DROP PROCEDURE loopLocations;
DROP PROCEDURE loopMenuItems;
```

**Comment by devawpshko** [comment]
Связано с задачей https://github.com/otrada-a/seo/issues/27
