### ISSUE TITLE
Использование шорткодов в блоке Seo основного домена

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#27]
Необходимо настроить поддержку шорткодов, используемых для seo-полей региональных поддоменов, в seo-полях основного домена с привязкой к Москве для гео-шорткодов:

Seo: Шорткоды

- {{ name }} название категории
- {{ location }} регион
- {{ location_to }} регион (куда)
- {{ location_where }} регион (где)

Шаблоны для Seo: Шорткоды

- {{ name }} название товара
- {{ price }} цена
- {{ parent_name }} название категории
- {{ product_prefix }} префикс
- {{ location }} регион
- {{ location_to }} регион (куда)
- {{ location_where }} регион (где)

Т.е., при использовании в поле "Заголовок страницы (Title)" на странице основного домена шаблона вида
`Купить в {{ location_where }}`
Для страниц основного домена должен формироваться title
`Купить в Москве`
Если для этой страницы не заполнено поле "Заголовок страницы (Title)" на региональном поддомене, то для страницы регионального поддомена (например, Ярославль) должен формироваться title
`Купить в Ярославле`

**Comment by Sadykov70** [comment]
@devawpshko я скоро выпущу задачу, где будет убрано `across Russia` (https://github.com/otrada-a/seo/issues/18)
Для доменов без региона вернутся дефолтные шаблоны:
en:
`page.product.seo.default_page_h1`: `{{ name }}`
`page.catalog.seo.default_page_title`: `{{ name }} - prices, reviews, delivery`
`page.catalog.seo.default_meta_description`: `View {{ name }} in the Furniprice catalog: a huge selection, affordable prices, convenient delivery in a short time`
ru:
`page.product.seo.default_page_h1`: `{{ name }}`
`page.catalog.seo.default_page_title`: `{{ name }} - цены, отзывы, доставка по России`
`page.catalog.seo.default_meta_description`: `Посмотреть {{ name }} в каталоге Furniprice: огромный выбор, доступные цены, удобная доставка по России в короткие сроки`

В админке меню можно настроить SEO поля для различных локалей
Например, для `ru` меню `Купить в Москве`
Это решит проблему?

**Comment by devawpshko** [comment]
@Sadykov70 мне кажется нет. Проблема в чем сейчас: вот у нас есть fp.ru, где для каких-то страниц прописан тайтл, содержащий слово "Москва" и этот же тайтл выводится на всех региональных поддоменах. Его можно уникализировать с помощью гео-шорткода, который работает на региональных поддоменах, но не работает на fp.ru.
Либо на региональных поддоменах должны использоваться только дефолтный шаблон и вручную заполненное значение.
Поэтому вариант, который в задаче описан, на мой взгляд, является оптимальным

**Comment by Sadykov70** [comment]
@devawpshko 
Я объясню логику:
Заходим на `spb.furniprice.ru`:
- у нас есть заполненый шаблон в `SEO -> Регионы -> spb -> Меню -> Диваны`,
выводим его `Купить {{ name }} в {{ location_where }} по цене {{ price }}`
- у нас нет шаблонов в `SEO -> Регионы -> spb -> Меню -> Диваны`,
выводим дефолтный `Купить {{ name }} в {{ location_where }}` _(пример)_

Заходим `www.furniprice.ru`:
- у нас есть заполненый SEO шаблон в `Меню -> Русское меню -> Диваны`,
выводим его `Купить {{ name }} в Москве`
- у нас нет SEO шаблонов в `Меню -> Русское меню -> Диваны`,
выводим дефолтный `Купить {{ name }} в России` _(пример)_

Когда мы будем находится на региональном поддомене, то мы не будем смотреть на СЕО шаблоны из  `Меню -> Русское меню -> Диваны`

Это все к вопросу в скайпе
> Вопрос - мы находимся на регион. домене, для которого нет установленных сео полей ни для одного меню итема через новый функционал. Но есть сео поля для в разделе меню. Будем мы выводить настроенные сео поля из этого меню? или выводим дефолтныеМарат Садыков, 

> 15:09
если не установлено, выводим дефолтные

**Comment by devawpshko** [comment]
Итог:
сделать дефолтный поддомен, где будет указываться шаблон заполнения seo-полей (категории меню и товары) для поддоменов, где эти шаблоны не заданы.

**Comment by grachevko** [comment]
@devawpshko в теории вы можете просто добавить страну с поддоменом `www` и получить то что хотите

**Comment by devawpshko** [comment]
@grachevko я бы предпочел не рисковать, делая это самостоятельно, чтобы ненароком не сломать что-то (=
