### ISSUE TITLE
Исправление карт сайта XML

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#3]
1. необходимо исправить адреса дочерних xml-карт в родительском sitemap.xml на полные, включающие https://www.
2. в дочерних xml-картах необходимо исправить урлы на валидные, начинающиеся с https://www.
3. в дочерних xml-картах, где есть документы на разных языках, например, статья на русском и польском, в блоке <url> должен также  содержать альтернейтив на саму себя
Например,  было:
```
<url>
    <loc>https://www.furniprice.ru/tips-and-tricks/category-3/jak-zachowac-jasne-wnetrze/</loc>
    <xhtml:link rel="alternate" hreflang="pl" href="https://www.furniprice.pl/tips-and-tricks/category-3/jak-zachowac-jasne-wnetrze/" />
</url>
```
согласно инструкции https://support.google.com/webmasters/answer/2620865?hl=ru&ref_topic=2370587 должно быть:
```
<url>
    <loc>https://www.furniprice.ru/tips-and-tricks/category-3/jak-zachowac-jasne-wnetrze/</loc>
    <xhtml:link rel="alternate" hreflang="pl" href="https://www.furniprice.pl/tips-and-tricks/category-3/jak-zachowac-jasne-wnetrze/" />
    <xhtml:link rel="alternate" hreflang="ru" href="https://www.furniprice.ru/tips-and-tricks/category-3/jak-zachowac-jasne-wnetrze/" />
</url>
```

4. нужно привести оформление карты сайта к читабельному виду по примеру:
http://www.vseinstrumenti.ru/vi_external_data/sitemaps/xml/www.vseinstrumenti.ru.1.xml
чтобы блоки были отделены друг от друга для удобства навигации и поиска ошибок

**Comment by grachevko** [comment]
3. Сейчас так и сделано. Ошибка в данном случае в том, что на домен `ru` польские статьи вообще не должны были попасть. Так как у нас статьи не переводимые. Одна статья - один язык. 
4. Есть предложения как это сделать, в чём у нас ошибка?

**Comment by grachevko** [comment]
1,2,3 - реализовано, ждёт делпоя.
4 - [ошиба](https://bugs.chromium.org/p/chromium/issues/detail?id=580033) браузере, предложено забить.

**Comment by devawpshko** [comment]
https://www.furniprice.ru/sitemap.xml
В основном сайтмапе полный урл до карт должен быть.
Т.е., вместо:
`<loc>sitemap.articles.xml</loc>`
должно быть:
`<loc>https://www.furniprice.ru/sitemap.articles.xml</loc>`
