### ISSUE TITLE
Убрать из карт сайта основные адреса других доменов

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#30]
В картах сайта в тегах `<loc></loc>` не должны выводиться ссылки на страницы с других доменов. Например, в https://www.furniprice.ru/sitemap.articles.xml сейчас выводится:
```
<url>
    <loc>https://www.furniprice.com/tips-and-tricks/category-3/boho-style-furniture-and-home-decor-ideas/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://www.furniprice.com/tips-and-tricks/category-3/boho-style-furniture-and-home-decor-ideas/"/>
  </url>
```

**Comment by Sadykov70** [comment]
@devawpshko 
В конкретном случае результат нужен такой
```
<url>
    <xhtml:link rel="alternate" hreflang="en" href="https://www.furniprice.com/tips-and-tricks/category-3/boho-style-furniture-and-home-decor-ideas/"/>
  </url>
```
или этот `url` убирается совсем

**Comment by devawpshko** [comment]
@Sadykov70 нужно целиком убирать весь этот URL

**Comment by devawpshko** [comment]
снова актуально: в картах сайтах между тегов `<loc></loc>` не должны показываться урлы с других языковых зон. Другие языковые зоны - только как альтернативные для основного адреса.

**Comment by Sadykov70** [comment]
Проверить акутальность после релиза https://github.com/otrada-a/seo/issues/45
