### ISSUE TITLE
Неверный хост в rel=canonical и адреса rel=alternate

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#36]
1) На части страниц основного домена зоны ru в теге `<link rel="canonical"` выводится не верный адрес страницы, в частности из зоны com
Пример:
страница https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/stoly/konsolnye-stoliki/p-yeh/
для нее выводится каноникал https://www.furniprice.com/catalog/zhilaia-mebel/gostinaia/stoly/konsolnye-stoliki/p-yeh/
а должна https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/stoly/konsolnye-stoliki/p-yeh/
Т.о., адрес каноничной страницы должен соответствовать домену (и поддомену для региональных страниц)

2) Для всех страниц неверно генерируются ссылки на альтернативные языковые версии, например:
https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/kresla-i-stulia/polukresla/p-banketka-iz-komplekta-skb/ имеет ссылки на альтернативные языки:
```
<link rel="alternate" href="//www.furniprice.com/catalog/zhilaia-mebel/gostinaia/kresla-i-stulia/polukresla/p-banketka-iz-komplekta-skb/" hreflang="en" />
<link rel="alternate" href="/catalog/zhilaia-mebel/gostinaia/kresla-i-stulia/polukresla/p-banketka-iz-komplekta-skb/" hreflang="ru" />
<link rel="alternate" href="//www.furniprice.cn/catalog/zhilaia-mebel/gostinaia/kresla-i-stulia/polukresla/p-banketka-iz-komplekta-skb/" hreflang="zh" />
```
таких урлов на www.furniprice.cn и www.furniprice.com не существует, отдается 404. Для альтернативных языков должен формироваться корректный URL.

**Comment by grachevko** [comment]
@devawpshko потому что описание товара только на английском есть
