### ISSUE TITLE
Уникализация меню региональных поддоменов

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#42]
**На утверждении**

На данный момент во всех меню региональных поддоменов в описании выводится текст, добавленный на основной домен. Нужно:
1) убрать вывод описания меню  с основного домена на региональных поддоменах (т.е. описание меню, добавленное на основном домене, должно выводиться только на основном домене).
2) в меню "Шаблоны" блока "SEO" у нас появилось доп. поле "Описание". Если выбран тип "Региональные поддомены" и сущность "Меню", то значение этого поля должно использоваться в качестве описания меню поддомена. Должна быть учтена возможность использования шорткодов.

**Comment by Sadykov70** [comment]
@devawpshko 

У нас сейчас есть функционал уникализации меню в `SEO` -> `Шаблоны`, например для питера задал описание в таком виде
![image](https://user-images.githubusercontent.com/38241587/44450017-806e8800-a5f8-11e8-8765-93746f0d51e1.png)

Переход на http://spb.furniprice.ru/catalog/zhilaia-mebel/gostinaia/divany/ , получил:
![image](https://user-images.githubusercontent.com/38241587/44450034-8f553a80-a5f8-11e8-8244-5e651392a310.png)

Я правильно понимаю, что нужно просто убрать данные описания www из описания регионалок?
