### ISSUE TITLE
Ошибки sitemap

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#45]
1. В основной карте сайта https://www.furniprice.ru/sitemap.xml отсутствуют ссылки на дополнительные карты сайта товаров. Необходимо их добавить.
Это: 
https://www.furniprice.ru/sitemap.products_0.xml
https://www.furniprice.ru/sitemap.products_1.xml

2. В карте сайта (отсутствует сам sitemap) отсутствуют ссылки на разделы меню. Нужно сделать дополнительную карту сайта с разделами меню, например, https://www.furniprice.ru/sitemap.cats.xml

3. Карта сайта view-source:https://www.furniprice.ru/sitemap.products.xml:
```
<url>
    <loc>https://www.furniprice.ru/catalog/zhilaia-mebel/prikhozhaia/dekory-i-aksessuary-dlia-prikhozhei/wall-mirrors/p-desma-gold-1/</loc>
    <xhtml:link rel="alternate" hreflang="ru" href="https://www.furniprice.ru/catalog/zhilaia-mebel/prikhozhaia/dekory-i-aksessuary-dlia-prikhozhei/wall-mirrors/p-desma-gold-1/"/>
  </url>
```
В карте сайта указана только 1 альтернативная ссылка на саму себя, хотя в коде страницы видно, что есть другие альтернативные версии:
```
<link rel="alternate" href="https://www.furniprice.com/catalog/furniture/living-room/living-room-decor-accessories/wall-mirrors-3/p-desma-gold-1/" hreflang="en" />
<link rel="alternate" href="https://www.furniprice.ru/catalog/zhilaia-mebel/prikhozhaia/dekory-i-aksessuary-dlia-prikhozhei/wall-mirrors/p-desma-gold-1/" hreflang="ru" />
<link rel="alternate" href="https://www.furniprice.cn/catalog/furniture/living-room/living-room-decor-accessories/wall-mirrors-3/p-desma-gold-1/" hreflang="zh" />
```
Необходимо, чтобы в картах сайта показывались все альтернативные версии страницы (кроме тех, что используют параметры)

4. Карта сайта view-source:https://www.furniprice.ru/sitemap.products_0.xml:
```
<url>
    <loc>https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/shkafy-i-stellazhi/navesnye-polki/p-avinion-4/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://www.furniprice.com/catalog/zhilaia-mebel/gostinaia/shkafy-i-stellazhi/navesnye-polki/p-avinion-4/"/>
    <xhtml:link rel="alternate" hreflang="pl" href="https://www.furniprice.pl/catalog/zhilaia-mebel/gostinaia/shkafy-i-stellazhi/navesnye-polki/p-avinion-4/"/>
  </url>
```
Отсутствует альтернативная ссылка на саму себя.

5. Карта сайта view-source:https://www.furniprice.ru/sitemap.products_1.xml:
```
 <url>
    <loc>https://www.furniprice.ru/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://www.furniprice.com/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/"/>
    <xhtml:link rel="alternate" hreflang="ru" href="https://www.furniprice.ru/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/"/>
    <xhtml:link rel="alternate" hreflang="zh" href="https://www.furniprice.cn/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/"/>
  </url>
```
Неверные адреса альтернативных версий страниц. Должны быть реальные адреса, а не те, что отдают 404 - иначе толку от таких альтернативных версий 0.

6. Доработка файлов Sitemap
Нужно добавить дополнительные параметры в каждый блок <url> внутренних файлов sitemap (товары, категории меню, статьи):
- `<lastmod></lastmod>` - между этими тегами должна выводиться дата последнего изменения страницы в формате https://www.w3.org/TR/NOTE-datetime (год, меся, число, час, минута, часовой пояс)
- `<changefreq></changefreq>` - этот тег нужно выводить для разделов меню и товаров со значением "weekly", для главной - "daily", для всех остальных страниц - "monthly"

Для основной карты сайта также необходимо указать `<lastmod></lastmod>` с датой и временем обновления и `<changefreq></changefreq>` со значением "daily".

Справка тут https://www.sitemaps.org/ru/protocol.html

**UPD 7. Не все товары выводятся в sitemap**
Например, есть товар https://www.furniprice.ru/catalog/zhilaia-mebel/vannaia-komnata/aksessuary-dlia-vannoi/laundry-hampers/p-mobel-oak-35/ его я не нашел ни в одном из файлов карт сайт. Нужно понять, почему он туда не был включен. Возможно, из-за того, что UK.

**Comment by Sadykov70** [comment]
> 5. Карта сайта view-source:https://www.furniprice.ru/sitemap.products_1.xml:
Неверные адреса альтернативных версий страниц. Должны быть реальные адреса, а не те, что отдают 404 - иначе толку от таких альтернативных версий 0.

Все ссылки из примера валидны:
https://www.furniprice.ru/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/ `200 OK`
https://www.furniprice.com/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/ `200 OK`
https://www.furniprice.cn/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/polutornye-krovati-shirina-120-150-sm/p-milana-27/ `200 OK`

**Comment by devawpshko** [comment]
Добавил 7й пункт.

**Comment by Sadykov70** [comment]
- [ ] 1. Ссылки на дополнительные карты сайта товаров (products_0, products_1)
- [ ] 2. Дополнительная карта сайта с разделами меню
- [ ] 3. В `sitemap.products.xml` показывать все альтернативные версии страницы (кроме тех, что используют параметры)
- [ ] 4. Карта сайта `view-source:https://www.furniprice.ru/sitemap.products_0.xml`:
Отсутствует альтернативная ссылка на саму себя.
- [ ] 5. Карта сайта `view-source:https://www.furniprice.ru/sitemap.products_1.xml`:
Неверные адреса альтернативных версий страниц. Должны быть реальные адреса, а не те, что отдают 404.

- [ ] 6. Добавить дополнительные параметры в каждый блок <url> внутренних файлов sitemap (товары, категории меню, статьи):
- `<lastmod></lastmod>` - дата последнего изменения страницы в формате https://www.w3.org/TR/NOTE-datetime (год, месяц, число, час, минута, часовой пояс)
- `<changefreq></changefreq>` - этот тег нужно выводить для разделов меню и товаров со значением "weekly", для главной - "daily", для всех остальных страниц - "monthly"
Для основной карты сайта также необходимо указать `<lastmod></lastmod>` с датой и временем обновления и `<changefreq></changefreq>` со значением "daily".

- [ ] 7. Не все товары выводятся в sitemap
