### ISSUE TITLE
Сгенерировать переводы описаний товаров

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#46]
**Предварительные вопросы:**
1. Какое суммарное количество товаров, выведенных на RU?
2. Сколько из этого числа имеют русское описание?
3. Сколько из этого числа имеют английское описание?
4. Сколько не имеют описания вообще?

**Первичная задача:**
Для товаров, у которых русское описание выполнено на английском, либо нет русской локализации, но есть английская, нужно сгенерировать перевод на русский язык и добавить его в русскую локализацию.

Задача разовая, связана с #40

**Comment by devawpshko** [comment]
Нужно посмотреть, почему у этих товаров нет перевода на русский:
https://www.furniprice.ru/catalog/aksessuary-i-dekor/aksessuary-dlia-ulitsy/aksessuary-dlia-rastenii/ulichnye-stoiki-dlia-rastenii/p-bamboo-2/
https://www.furniprice.ru/catalog/aksessuary-i-dekor/garderobnaia/veshalki-kriuchki-i-plechiki/kriuchki-2/p-crazy-head/
https://www.furniprice.ru/catalog/aksessuary-i-dekor/garderobnaia/veshalki-kriuchki-i-plechiki/napolnye-veshalki-1/p-medusa/

Также нужно проверить в БД товары, где отсутствует русский перевод описания

**Comment by Sadykov70** [comment]
запрос
```
select sku, group_concat(translation.locale) locales from product
left join product_translation translation on product.id = translation.translatable_id
group by product.sku
having locales not like '%ru%'
```
Показал, что у `14680` нет перевода на русский

**Comment by grachevko** [comment]
@devawpshko у указанных товаров нет русского перевода, потому что оригинальное описание у них на итальянском. 
Английский перевод у них это машинный перевод с итальянского.

**Comment by devawpshko** [comment]
@Sadykov70  @grachevko Тогда для этих товаров нужно сгенерировать русский перевод с Итальянского на Русский

**Comment by grachevko** [comment]
@devawpshko в задаче было написано только с английского. Если надо с других языков открывайте новую задачу.
