### ISSUE TITLE
Хлебные крошки в виде ссылок <a>

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#48]
Для разделов меню и карточек товаров основного домена и поддоменов необходимо внесети изменения в верстку:
вывод хлебных крошек ветки должен выполняться с помощью тега <a>, где в атрибуте href должны передаваться ссылки на родительские страницы.

Например:
https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/divany/divany-priamye/p-lokken-1/
Главная / Мебель для дома / Гостиная / Диваны / Диваны прямые - должны быть сделаны ссылками. В хлебных крошках с выпадающими элементами - генерацию выпадающих элементов оставить текущей (без ссылок <a>).

**Comment by Sadykov70** [comment]
Для элементов крошек, которые имеют раскрывающийся список вместо тега `span` использовать `a` с нужным аттрибутом `href` (см. описание задачи).
Все элементы в раскрывающихся списках должны работать по прежней логике и их не нужно превращать в `a`.
