### ISSUE TITLE
404 ошибка пагинации продавцов в товарах

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#53]
После обновления карточки было сделано разделение продавцов на тех, что привязаны к текущему региону, и всех вместе.

Из-за этого количество страниц пагинации выбранного региона уменьшилось (либо сократилось до 1 страницы), а для построения пагинации всех продавцов используется дополнительный параметр в урле после последнего слэша `?allSellers=true`, а сам параметр пагинации находился в конце `?allSellers=true&page=3`

Т.о., проиндексированные страницы пагинации стали массово отдавать 404 ответ.

Необходимо вернуть прежнюю систему пагинации для контактов всех продавцов:
использование единичного параметра в урле `?page=***`
И скорректировать вывод продавцов текущего региона:
добавить после параметра `?page=***` дополнительный параметр, отвечающий за выборку производителей в этом регионе, например, `&currentRegion=true`

**Крайне очень сильно важная задача**, т.к. у нас с каждым днем число 404, которые видит робот растет. И сейчас их уже около 11 тыс.

**Comment by Sadykov70** [comment]
Стас:
> По дефолту на карточке товара допустимо сделать максимальную дистанцию для продавцов

**Comment by devawpshko** [comment]
ок
