### ISSUE TITLE
Нет ссылки на личный кабинет в мобильной версии

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#56]
При переключении на мобильную версию сайта (открытии с мобильного устройства) в верхней центральной части  появляется иконка входа в личный кабинет, но на иконку не назначено никакого действия / ссылки.
https://yadi.sk/i/OqVIU63_3RNjRA

Если в мобильной версии пользователь должен иметь возможность входа в личный кабинет, то необходимо добавить действие для аутентификации при нажатии на иконку.

Если аутентификация не предусмотрена для мобильных пользователей, то необходимо убрать эту иконку.

**Comment by Sadykov70** [comment]
При клике на иконку добавить переход на урл https://www.furniprice.ru/login
![image](https://user-images.githubusercontent.com/38241587/46194940-89dfc400-c30b-11e8-8513-3f41b1adc26f.png)
