### ISSUE TITLE
Дублирование карточек товаров

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#57]
В индексе яндекса фигурирует достаточно большое число страниц с пометкой "Дубль" (1000).
Примеры:
https://www.furniprice.ru/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/dvuspalnye-krovati-queen-size-shirina-150-170-sm/p-narciso-14/
https://www.furniprice.ru/catalog/zhilaia-mebel/spalnia/krovati-i-izgolovia/dvuspalnye-krovati-queen-size-shirina-150-170-sm/p-narciso-13/
(товары находятся в 1 категории, являются идентичными по контенту, но имеют разные карточки)

https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/ottomanki-i-banketki/ottomanki/p-pouffe/
https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/ottomanki-i-banketki/pufy/p-pouffe/
(товары находятся в в разных меню, на одном уровне в одной ветке)

https://www.furniprice.ru/catalog/aksessuary-i-dekor/spalnia-1/tekstil-dlia-spalni/dekorativnye-podushki/p-chrysanthemum/
https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/dekor-i-aksessuary-dlia-gostinykh/decorative-pillows-1/p-chrysanthemum/
(идентичные товары, находятся в разных ветках)

Необходимо сначала уточнить: это один и тот же товар, имеющий привязку к нескольким меню, или 2 разных товара?

Если это один товар с мультипривязкой, ТО в коде карточки товара должен быть прописан тег `<link rel="canonical" href=""/>` c атрибутом `href=""`, содержащим полный адрес товара по основной привязке.
Если у товара нет основной привязки (если она в принципе не предусмотрена), то основной привязкой нужно считать первую указанную категорию меню.

Цель задачи: товар должен быть доступен по единому адресу, иначе происходит дублирование, что негативно сказывается на продвижении в ПС.

**Comment by Sadykov70** [comment]
Duplicate of https://github.com/otrada-a/seo/issues/62
