### ISSUE TITLE
Переключение языков на сайте

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#58]
Необходимо реализовать корректное переключение языков на сайте. В настоящий момент при переключении между языковыми зонами выполняется перенаправление на страницу языковой зоны с сохранением структуры адресов.

Пример:
(ENG) https://www.furniprice.com/catalog/furniture/living-room/tables/coffee-tables/ -> (PL) https://www.furniprice.pl/catalog/furniture/living-room/tables/coffee-tables/

Т.о., у нас возникает проблема с меню - все переключения с RU на любую другую языковую зону отдают 404.

Нужно выполнять сопоставление расположение товара относительно меню и выполнять перенаправление на соответствующий товар в соответствующем меню языковой зоны. Если товар отсутствует в соответствующем меню на переключемой языковой зоне, то проверять каноничный адрес и выполнять перенаправление на каноничный адрес.

Если товар отсутствует в принципе и для него нет каноничного урла на переключаемой языковой зоне, то отдавать 404 ошибку по адресу переключения (т.е. сохранять предыдущий путь до товара включительно).

Для категорий меню: выполнять проверку соответствия меню между языковыми зонами и выполнять перенаправление, чтобы избежать отдачи 404 из-за разных вариантов записи меню.

Если меню не существует в принципе на переключаемой языковой зоне, то отдавать 404 ошибку по адресу переключения.

Переключение необходимо выполнять без дополнительных перенаправления с урлов с параметрами - "?lang=de". Т.е., 302 код должен отдаваться со страницы переключения на переключаемую страницу.

Смежно с комментарием в задаче #17

**Comment by Sadykov70** [comment]
Будет использоваться функционал задачи otrada-a/furniprice#2533

**Comment by grachevko** [comment]
> Переключение необходимо выполнять без дополнительных перенаправления с урлов с параметрами - "?lang=de"

В чём смысл данного условия?

**Comment by devawpshko** [comment]
Это дополнительная цепочка при переключении языка. На текущий момент получается, что пользователь, переключив язык, остается на той же странице, но добавляется параметр к урлу, и только потом - редирект.

Плюс опирался на сайты конкурентов и других мультиязычных/мультирегиональных сайтов.

**Comment by grachevko** [comment]
Клиент всё равно никак не замечает цепочек редиректов. Контент между редиректами он не получает и вообще не замечает что его редиректит куда то. Боты по этим редиректам не ходят.

**Comment by devawpshko** [comment]
тогда пока заморозим задачу, буду уточнять дальше
