### ISSUE TITLE
Не работают шаблоны мета-тегов для зоны COM

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#59]
Не работают шаблоны мета-тегов для языковой зоны COM. В админке соответствующие шаблоны прописаны.

Примеры страниц
https://www.furniprice.com/catalog/accessories-decor/kitchen-dining-2/flatware/flatware-sets/p-childrens-spanner-cutlery-set/
https://www.furniprice.com/catalog/accessories-decor/kitchen-dining-2/flatware/

**Comment by Sadykov70** [comment]
@devawpshko, уточни, пож-та, что именно не работает.
Проверил, что все поля шаблона выводятся корректно
![image](https://user-images.githubusercontent.com/38241587/45867594-745b1f00-bd8c-11e8-9ff2-a0d08d89d1b4.png)

**Comment by devawpshko** [comment]
@Sadykov70 я имею ввиду, что на сайте не выводятся шаблоны. Например, для товара зоны com у нас шаблон `{{ name }} - prices, reviews, delivery`, но на сайте выводится просто `Furniprice`

**Comment by Sadykov70** [comment]
@devawpshko закрываем?

**Comment by devawpshko** [comment]
да)
