### ISSUE TITLE
Задачи по canonical: дублирующиеся товары

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#62]
Если товар имеет привязку к нескольким меню одновременно, из-за чего один и тот же товар доступен по разным ссылкам, необходимо в качестве каноничного адреса в теге <link rel="canonical" href=""> указывать URL основной привязки (т.е., той, которая добавлена раньше).

Важное дополнение про страницы пагинации: задача относится в том числе к "образующим" страницам (пагинации, параметрам и т.п.) - каноничным урлом для них также будет URL товара по основной привязке.

Пример:
основная привязка товара - https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/divany/kushetki/p-gloriia/
вторичная привязка - https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/ottomanki-i-banketki/kushetki/p-gloriia/

Т.о., для страницы пагинации https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/ottomanki-i-banketki/kushetki/p-gloriia/?page=666 каноничным будет URL https://www.furniprice.ru/catalog/zhilaia-mebel/gostinaia/divany/kushetki/p-gloriia/

Задача актуальна для товаров всех основных доменов и поддоменов.

**Comment by Sadykov70** [comment]
Будет использоваться функионал задачи https://github.com/otrada-a/furniprice/issues/2533
