### ISSUE TITLE
Задачи по canonical: другие языковые версии

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#63]
Задача пересекается с задачей #62 
В качестве альтернативных ссылок на другие языковые версии для товаров должны использоваться каноничные адреса, сформированные по основной привязке.

Т.о., если для товара есть альтернативная языковая версия, то ссылка на эту альтернативную языковую версию должна формироваться относительно основной привязки товара (по первой привязанной категории меню).

Важное уточнение: у нас может быть товар, который есть в одной категории на RU, но на COM он находится в другой категории. В этом случае для них также должна быть сформированы ссылки на альтернативные языковые версии.

Задача актуальна для всех языковых версий сайта, НО не для региональных поддоменов RU.

**Comment by Sadykov70** [comment]
Будет использоваться функионал задачи https://github.com/otrada-a/furniprice/issues/2533
