### ISSUE TITLE
Изменение SEO-полей для служебных страниц

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#7]
Доброго дня!
Нужно изменить поля title и meta-description для следующих страниц:

* Контакты:
Title: Контактная информация Furniprice.

* О нас:
Title: Информация о компании Furniprice.

* Советы и идеи
Title: Советы и идеи для дома, ремонта рекомендации по выбору мебели от Furniprice.
Meta-description: Специалисты Furniprice подготовили полезные статьи на тему ремонта квартиры и дома, строительства, выбора, покупки и расстановки мебели.

* Для инвесторов:
Title: Информация для инвесторов.

*Главная (**нужно ли согласование seo-полей для этой страницы?**):
Title: Furniprice - многофункциональное пространство по подбору мебели 
и предметов интерьера.
Meta-description: Платформа Furniprice объединяет покупателей, дизайнеров и продавцов мебели со всего мира, делая процесс покупки и поиска клиентов проще.

**Comment by Sadykov70** [comment]
> Советы и идеи для дома, ремонта рекомендации по выбору мебели от Furniprice.
После слова
> ремонта
нужная запятая?

**Comment by devawpshko** [comment]
> После слова ремонта нужная запятая?
Да, пардон.
Советы и идеи для дома, ремонта, рекомендации по выбору мебели от Furniprice.

**Comment by dsemyonov** [comment]
Для страницы - "Стать продавцом" ничего не надо?
