### ISSUE TITLE
Исправить robots.txt

### ISSUE THREAD

**Issue by devawpshko** [otrada-a/seo#74]
Файл https://www.furniprice.ru/robots.txt на основном домене отдает 502 ошибку и не доступен для поискового робота. Необходимо восстановить его доступность.

**Comment by Sadykov70** [comment]
@devawpshko а сейчас?
перешел по ссылке
![image](https://user-images.githubusercontent.com/38241587/48137925-2f476980-e2b4-11e8-9328-a8b302630f97.png)

наверно из-за того что бой падал

**Comment by devawpshko** [comment]
ну тогда ладно)
